
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_HEADER_SEARCH = 'SET_HEADER_SEARCH'

// authentication
const AUTH = 'AUTH'
export const AUTHENTICATE = `${AUTH}_AUTHENTICATE`
export const DEAUTHENTICATE = `${AUTH}_DEAUTHENTICATE`


//
const EVENT = 'EVENT'
export const SET_EVENTS_LOADING = `${EVENT}SET_EVENTS_LOADING`
export const SET_EVENTS = `${EVENT}_SET_EVENTS`
export const SET_SINGLE_EVENT = `${EVENT}_SET_SINGLE_EVENT`
export const SET_CATEGORIES = `${EVENT}_SET_CATEGORIES`
export const SET_SEARCH_CRITERIA = `${EVENT}_SET_SEARCH_CRITERIA`

const USER = 'USER'
export const SET_USER = `${USER}_SET_USER`
export const SET_CURRENT_USER = `${USER}_SET_CURRENT_USER`
